[package]
name = "facet-core"
version = "0.12.0"
authors = [
    "Amos Wenger <amos@bearcove.eu>",
    "Lukas Wirth <lukastw97@gmail.com>",
]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Core types and traits for the facet ecosystem"
keywords = ["reflection", "core"]
categories = ["development-tools"]

[features]
default = ["std"]
std = ["alloc"]
alloc = []
camino = ["dep:camino", "alloc"]
ordered-float = ["dep:ordered-float"]
uuid = ["alloc", "dep:uuid"]

[dependencies]
impls = "1.0.3"
bitflags = "2.9.0"
camino = { version = "1", optional = true }
ordered-float = { version = "5.0.0", optional = true, default-features = false }
uuid = { version = "1.16.0", optional = true }

[dev-dependencies]
facet-testhelpers = { path = "../facet-testhelpers" }
